CREATE TABLE [dbo].[CharacterTable] (
    [characterName]         VARCHAR (512) NOT NULL,
    [characterGender]       VARCHAR (512) NOT NULL,
    [characterHairStyle]    VARCHAR (512) NOT NULL,
    [characterFacialHair]   VARCHAR (512) NOT NULL,
    [characterHairColor]    VARCHAR (512) NOT NULL,
    [characterSkinColor]    VARCHAR (512) NOT NULL,
    [characterTattoos]      VARCHAR (512) NOT NULL,
    [characterMarkings]     VARCHAR (512) NOT NULL,
    [characterAge]          VARCHAR (512) NOT NULL,
    [characterEyeColor]     VARCHAR (512) NOT NULL,
    [characterHeight]       VARCHAR (512) NOT NULL,
    [characterWidth]        VARCHAR (512) NOT NULL,
    [characterAccessories]  VARCHAR (512) NOT NULL,
    [characterUpperBodyC]   VARCHAR (512) NOT NULL,
    [characterUBStyle]      VARCHAR (512) NOT NULL,
    [characterLowerBodyC]   VARCHAR (512) NOT NULL,
    [characterLBStyle]      VARCHAR (512) NOT NULL,
    [characterFootwear]     VARCHAR (512) NOT NULL,
    [characterRace]         VARCHAR (512) NOT NULL,
    [characterClass]        VARCHAR (512) NOT NULL,
    [characterKeepsakes]    VARCHAR (512) NOT NULL,
    [characterSTR]          INT           NOT NULL,
    [characterDEX]          INT           NOT NULL,
    [characterCON]          INT           NOT NULL,
    [characterINT]          INT           NOT NULL,
    [characterWIS]          INT           NOT NULL,
    [characterCHA]          INT           NOT NULL,
    [characterAGI]          INT           NOT NULL,
    [characterVIT]          INT           NOT NULL,
    [characterPER]          INT           NOT NULL,
    [characterLUK]          INT           NOT NULL,
    [characterWIL]          INT           NOT NULL,
    [characterFOR]          INT           NOT NULL,
    [characterARC]          INT           NOT NULL,
    [characterTEC]          INT           NOT NULL,
    [characterSTL]          INT           NOT NULL,
);

